# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to amazon-issued-cert module."
  name: ":floppy_disk: amazon-issued-cert"
- color: "fbca04"
  description: "This issue or pull request is related to cidr-collection module."
  name: ":floppy_disk: cidr-collection"
- color: "fbca04"
  description: "This issue or pull request is related to imported-cert module."
  name: ":floppy_disk: imported-cert"
- color: "fbca04"
  description: "This issue or pull request is related to private-ca-issued-cert module."
  name: ":floppy_disk: private-ca-issued-cert"
- color: "fbca04"
  description: "This issue or pull request is related to private-zone module."
  name: ":floppy_disk: private-zone"
- color: "fbca04"
  description: "This issue or pull request is related to public-zone module."
  name: ":floppy_disk: public-zone"
- color: "fbca04"
  description: "This issue or pull request is related to registered-domain module."
  name: ":floppy_disk: registered-domain"
- color: "fbca04"
  description: "This issue or pull request is related to resolver-inbound-endpoint module."
  name: ":floppy_disk: resolver-inbound-endpoint"
- color: "fbca04"
  description: "This issue or pull request is related to resolver-query-logging module."
  name: ":floppy_disk: resolver-query-logging"
