# Modules
- color: "fbca04"
  description: "This issue or pull request is related to cidr-collection module."
  name: ":floppy_disk: cidr-collection"
- color: "fbca04"
  description: "This issue or pull request is related to private-zone module."
  name: ":floppy_disk: private-zone"
- color: "fbca04"
  description: "This issue or pull request is related to profile module."
  name: ":floppy_disk: profile"
- color: "fbca04"
  description: "This issue or pull request is related to public-zone module."
  name: ":floppy_disk: public-zone"
- color: "fbca04"
  description: "This issue or pull request is related to record-set module."
  name: ":floppy_disk: record-set"
- color: "fbca04"
  description: "This issue or pull request is related to registered-domain module."
  name: ":floppy_disk: registered-domain"
- color: "fbca04"
  description: "This issue or pull request is related to resolver-inbound-endpoint module."
  name: ":floppy_disk: resolver-inbound-endpoint"
- color: "fbca04"
  description: "This issue or pull request is related to resolver-query-logging module."
  name: ":floppy_disk: resolver-query-logging"
